name: Pull Request
on:  
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  title:
    name: Ensure that title uses gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/gitmoji@v2.1.3

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@v2.1.3
  
  build:
    name: Build
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@v2.1.3
      - run: yarn build

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@v2.1.3
      - run: yarn lint

  test:
    name: Run testing
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@v2.1.3
      - run: yarn test --coverage

    
