name: pull-request
on:
  pull_request:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install node_modules
        run: npm clean-install
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm run test
      